### ISSUE TITLE
🚀 [Technology] Phát triển công nghệ cho tương lai

### ISSUE THREAD

**Issue by thongnmtran** [minhthongit2015/alpha-research-central#37]
#### Tham khảo
- [x] [OGarden](https://gigadgets.com/2019/05/13/this-machine-grows-crops-in-a-month-without-needing-an-actual-garden): [Video Giới thiệu](https://drive.google.com/file/d/15r299dwDXZEFwFzLs1clJ82qGIpnVyxO/view?usp=sharing)
- [x] Bios: [Video Giới thiệu](https://drive.google.com/file/d/1ZWjmUx0dSalZ_DEV4_TSFrTW0LgXgMDL/view?usp=sharing)

#### Của chúng ta:
- [ ] Lọc không khí Ion-âm: [Chi tiết](https://github.com/minhthongit2015/alpha-research-central/issues/11)
- [ ] Bình hoa/Chậu cây vạn niêm: [Chi tiết](https://github.com/minhthongit2015/alpha-research-central/issues/13)
- [ ] Dùng Năng lượng sạch: [Chi tiết](https://github.com/minhthongit2015/alpha-research-central/issues/14)
- [ ] Đuổi côn trùng
- [ ] Sáp thơm
- [ ] Phát nhạc
- [ ] Đài radio
- [ ] Trò chuyện
- [ ] Rạp chiếu phim
- [ ] Máy phun sương làm mát
- [ ] Máy sưởi
- [ ] Máy sấy quần áo
